version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis_cache
    hostname: redis_cache
    restart: always
    ports:
      - 6379:6379
    volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./redis/cache:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server /usr/local/etc/redis/redis.conf
